# Generated by Django 5.0.7 on 2025-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmcvweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='archivo',
            field=models.FileField(upload_to='media/inicio'),
        ),
    ]
