# Generated by Django 5.0.7 on 2025-02-23 23:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmcvweb', '0002_alter_inicio_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('enlace', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('imagen', models.ImageField(upload_to='media/aplicacion')),
                ('archivo', models.FileField(upload_to='media/aplicacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='media/presentacion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/presentacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre de la actividad')),
                ('fechaact', models.DateField(verbose_name='Fecha del evento')),
                ('contenido', models.TextField(verbose_name='Descripcion del Evento')),
                ('imagen', models.ImageField(upload_to='media/actividades')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/actividades')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmcvweb.grupo', verbose_name='Area Encargada')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fechaact'],
            },
        ),
        migrations.CreateModel(
            name='comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del comunicado')),
                ('fechaact', models.DateField(verbose_name='Fecha')),
                ('archivo', models.FileField(upload_to='media/comunicados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmcvweb.grupo', verbose_name='Area Encargada')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-fechaact'],
            },
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='media/publicaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/publicaciones')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmcvweb.grupo')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['updated'],
            },
        ),
    ]
